name: Compilar LaTeX a PDF automáticamente

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Ncombinatorios.tex

      - name: Guardar PDF en el repositorio
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@://github.com'
          
          # Crear carpeta si no existe y mover el PDF generado
          mkdir -p PDFs
          mv Ncombinatorios.pdf PDFs/
          
          # Confirmar y subir cambios de forma directa
          git add PDFs/Ncombinatorios.pdf
          git commit -m "Actualiza el PDF compilado automáticamente [skip ci]" || exit 0
          git push origin main
